packer {
  required_plugins {
    virtualbox = {
      source  = "github.com/hashicorp/virtualbox"
      version = "~> 1"
    }
  }
}

source "virtualbox-iso" "autogenerated_1" {
  boot_wait            = "5s"
  communicator         = "none"
  disk_size            = 61440
  
  # CAMBIO 1: Usamos cd_files en lugar de floppy_files.
  # Isto crea un CD-ROM virtual que admite ficheiros grandes.
  # Asegúrate de que SQLEXPR_x64_ENU.exe está neste cartafol.
  cd_files = [
    "./Autounattend.xml",
    "./configure.ps1",
    "./SQLEXPR_x64_ENU.exe"
  ]
  
  guest_additions_mode = "disable"
  guest_os_type        = "Windows2019_64"
  headless             = false
  cpus                 = 2
  memory               = 4096

  iso_checksum         = "sha256:002cb53ecb87b9287cb36eea991f3d26841646bef962d1a48d75d450b87de2d3"
  iso_url              = "./isos/17763.3650.221105-1748.rs5_release_svc_refresh_SERVER_EVAL_x64FRE_es-es.iso"

  virtualbox_version_file = ""
  shutdown_timeout     = "90m"
  shutdown_command     = "echo 'Script xestiona apagado'"
  vm_name              = "VULN-DC-01"

  # REDE HOST-ONLY (Sen internet, todo offline dende o principio)
  vboxmanage = [
    ["modifyvm", "VULN-DC-01", "--nic1", "hostonly"],
    ["modifyvm", "VULN-DC-01", "--hostonlyadapter1", "vboxnet0"], 
    ["modifyvm", "VULN-DC-01", "--nictype1", "82540EM"],
    ["modifyvm", "VULN-DC-01", "--graphicscontroller", "vboxsvga"],
    ["modifyvm", "VULN-DC-01", "--vram", "128"],
    ["modifyvm", "VULN-DC-01", "--groups", "/HE/Templates"]
  ]
}

build {
  sources = ["source.virtualbox-iso.autogenerated_1"]
  # Xa non hai provisioners, todo vai no CD
}
